.\" man page create by R# package system.
.TH GNUPLOT 1 2000-Jan "config" "config"
.SH NAME
config \- config of the gnuplot executable file path
.SH SYNOPSIS
\fIconfig(\fBgnuplot\fR as string);\fR
.SH DESCRIPTION
.PP
config of the gnuplot executable file path
.PP
.SH OPTIONS
.PP
\fBgnuplot\fB \fR\- the user configed custom gnuplot path location.. 
.PP
.SH SEE ALSO
GNUplot
.SH FILES
.PP
GNUplot.dll
.PP
