.\" man page create by R# package system.
.TH GNUPLOT 1 2000-Jan "scatter" "scatter"
.SH NAME
scatter \- Create x,y scatter plot
.SH SYNOPSIS
\fIscatter(\fBx\fR as any, 
\fBy\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Create x,y scatter plot
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBy\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
GNUplot
.SH FILES
.PP
GNUplot.dll
.PP
